import test from 'node:test';
import assert from 'node:assert/strict';
import { elapsedSeconds, equalWeights, formatDuration, lensWeights, normalizeWeights, rankEngineers } from '../src/lib/ranking.ts';
import type { ImpactData, Outcome } from '../src/lib/types.ts';
function outcome(id:string, significance:1|3|5, dimension:Outcome['dimension']='product', people=['a']):Outcome{return {id,initiativeId:id,title:id,summary:'',benefit:'',dimension,significance,significanceRationale:'',confidence:'documented',stage:'Merged',verified:true,evidenceIds:['source'],participants:people.map(engineerId=>({engineerId,role:'Driver',rationale:'',evidenceIds:['source']})),metrics:[],followUp:'',limitations:[]};}
function data(outcomes:Outcome[]):ImpactData{return {version:'1',manifest:{} as ImpactData['manifest'],engineers:[{id:'a',name:'Alice',avatar:'',url:''},{id:'b',name:'Bob',avatar:'',url:''}],initiatives:[],outcomes,evidence:[]};}
test('only the strongest three distinct outcomes count, not PR or duplicate volume',()=>{const one=outcome('one',5);const ranked=rankEngineers(data([one,one,outcome('two',3),outcome('three',1),outcome('four',1)]),lensWeights('product'));assert.equal(ranked[0].score,9);assert.equal(ranked[0].outcomes.length,3);});
test('changing priorities reranks the whole assessed population',()=>{const fixture=data([outcome('product',5,'product',['a']),outcome('devex',3,'devex',['b'])]);assert.equal(rankEngineers(fixture,lensWeights('product'))[0].engineer.id,'a');assert.equal(rankEngineers(fixture,lensWeights('devex'))[0].engineer.id,'b');});
test('substantive shared contribution receives credit and equal scores share ranks',()=>{const ranked=rankEngineers(data([outcome('shared',5,'reliability',['a','b'])]),equalWeights);assert.deepEqual(ranked.map(r=>[r.engineer.id,r.rank]),[['a',1],['b',1]]);});
test('unsupported outcomes and undocumented attribution are excluded',()=>{const unverified=outcome('unverified',5);unverified.verified=false;const missing=outcome('missing',5);missing.participants[0].evidenceIds=[];assert.equal(rankEngineers(data([unverified,missing]),equalWeights).length,0);});
test('negative, zero, and invalid priorities are safely normalized',()=>{const weights=normalizeWeights({...equalWeights,product:-10,performance:NaN});assert.equal(weights.product,0);assert.equal(weights.performance,0);assert.equal(Object.values(weights).reduce((a,b)=>a+b,0),1);assert.equal(normalizeWeights({product:0,reliability:0,performance:0,devex:0,leverage:0,simplification:0}).product,1/6);});
test('timer derives from absolute timestamps and does not cap at 90 minutes',()=>{const run={startedAt:'2026-10-04T21:30:00Z',stoppedAt:null};assert.equal(elapsedSeconds(run,Date.parse('2026-10-04T23:10:00Z')),6000);assert.equal(formatDuration(6000),'01:40:00');assert.equal(elapsedSeconds({...run,stoppedAt:'2026-10-04T22:47:42Z'},Date.parse('2026-10-05T00:00:00Z')),4662);});
